question_bank = [
    {"question": "Is Python a statically typed language?", "answer": False},
    {"question": "Is 'print' a keyword in Python 3?", "answer": False},
    {"question": "Is 'import' used to include external libraries?", "answer": True},
    {"question": "Is Python case-sensitive?", "answer": True},
    {"question": "Can you declare a variable without assigning a value in Python?", "answer": False},
    {"question": "Is 'append()' used to add elements to a list?", "answer": True},
    {"question": "Is the 'finally' block in a try-except structure always executed?", "answer": True},
    {"question": "Can you inherit from multiple classes in Python?", "answer": True},
    {"question": "Does 'set' store duplicate values?", "answer": False},
    {"question": "Can 'int' and 'str' be added directly in Python?", "answer": False},
    {"question": "Is 'True' a boolean value in Python?", "answer": True},
    {"question": "Can a Python tuple be modified after creation?", "answer": False},
    {"question": "Is 'global' used to modify a global variable inside a function?", "answer": True},
    {"question": "Are Python dictionaries unordered?", "answer": False},
    {"question": "Is 'type()' used to get the type of a variable?", "answer": True},
    {"question": "Does 'range(5)' include the number 5?", "answer": False},
    {"question": "Is 'is' used for identity comparison in Python?", "answer": True},
    {"question": "Does Python have a switch-case statement?", "answer": False},
    {"question": "Is 'yield' used in generators?", "answer": True},
    {"question": "Can you open a file using 'with open() as f:' in Python?", "answer": True},
    {"question": "Is a list comprehension faster than a for loop in Python?", "answer": True},
    {"question": "Can 'break' be used outside loops?", "answer": False},
    {"question": "Does 'try' require at least one 'except' or 'finally' block?", "answer": True},
    {"question": "Is 'pass' a no-operation statement in Python?", "answer": True},
    {"question": "Can functions in Python be assigned to variables?", "answer": True},
    {"question": "Can you create a GUI using only Python?", "answer": True},
    {"question": "Is the index of the first item in a list 1?", "answer": False}
]
